---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sloth.fullname" . }}
  namespace: {{ .Values.sloth.namespace }}
  labels:
    {{- include "sloth.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "sloth.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sloth.fullname" . }}
    namespace: {{ .Release.Namespace }}
